const products = [
  {
    id: 1,
    title: "Espresso",
    price: 150,
    image: "./assets/feature-1.jpg",
    quantity: 1,
    description: "A strong and bold single shot of pure coffee with rich crema.",
    category: "espresso",
    available: true,
    feature: true,
    createdAt: "09:00",
  },
  {
    id: 2,
    title: "Cappuccino",
    price: 220,
    image: "./assets/feature-2.jpg",
    quantity: 1,
    description: "Perfect balance of espresso, steamed milk, and milk foam.",
    category: "cappuccino",
    available: true,
    feature: true,
    createdAt: "09:15",
  },
  {
    id: 3,
    title: "Caffè Latte",
    price: 210,
    image: "./assets/feature-3.jpg",
    quantity: 1,
    description: "Smooth espresso blended with creamy steamed milk.",
    category: "latte",
    available: true,
    feature: true,
    createdAt: "09:30",
  },
  {
    id: 4,
    title: "Mocha",
    price: 240,
    image: "./assets/feature-3.jpg",
    quantity: 1,
    description: "Espresso mixed with rich chocolate syrup and steamed milk.",
    category: "mocha",
    available: true,
    feature: false,
    createdAt: "10:00",
  },
  {
    id: 5,
    title: "Americano",
    price: 180,
    image: "./assets/feature-3.jpg",
    quantity: 1,
    description: "Espresso diluted with hot water for a smooth, bold taste.",
    category: "americano",
    available: true,
    feature: false,
    createdAt: "10:15",
  },
  {
    id: 6,
    title: "Flat White",
    price: 230,
    image: "./assets/feature-3.jpg",
    quantity: 1,
    description: "Velvety steamed milk poured over a double shot of espresso.",
    category: "flat white",
    available: true,
    feature: false,
    createdAt: "10:30",
  },
  {
    id: 7,
    title: "Caramel Latte",
    price: 260,
    image: "./assets/feature-3.jpg",
    quantity: 1,
    description: "Creamy latte flavored with sweet caramel syrup.",
    category: "latte",
    available: true,
    feature: false,
    createdAt: "11:00",
  },
  {
    id: 8,
    title: "Vanilla Latte",
    price: 250,
    image: "./assets/feature-3.jpg",
    quantity: 1,
    description: "Classic latte infused with smooth vanilla flavor.",
    category: "latte",
    available: true,
    feature: false,
    createdAt: "11:15",
  },
  {
    id: 9,
    title: "Hazelnut Cappuccino",
    price: 255,
    image: "./assets/feature-3.jpg",
    quantity: 1,
    description: "Cappuccino enhanced with nutty hazelnut syrup.",
    category: "cappuccino",
    available: true,
    feature: false,
    createdAt: "11:30",
  },
  {
    id: 10,
    title: "Macchiato",
    price: 170,
    image: "./assets/feature-3.jpg",
    quantity: 1,
    description: "Espresso topped with a small amount of milk foam.",
    category: "espresso",
    available: true,
    feature: false,
    createdAt: "11:45",
  },
  {
    id: 11,
    title: "White Chocolate Mocha",
    price: 270,
    image: "./assets/feature-3.jpg",
    quantity: 1,
    description: "Sweet white chocolate blended with espresso and milk.",
    category: "mocha",
    available: true,
    feature: false,
    createdAt: "12:00",
  },
  {
    id: 12,
    title: "Iced Latte",
    price: 230,
    image: "./assets/feature-3.jpg",
    quantity: 1,
    description: "Chilled espresso with cold milk and ice.",
    category: "latte",
    available: true,
    feature: false,
    createdAt: "12:15",
  },
  {
    id: 13,
    title: "Iced Americano",
    price: 190,
    image: "./assets/feature-3.jpg",
    quantity: 1,
    description: "Cold water poured over espresso with ice.",
    category: "americano",
    available: true,
    feature: false,
    createdAt: "12:30",
  },
  {
    id: 14,
    title: "Double Espresso",
    price: 200,
    image: "./assets/feature-3.jpg",
    quantity: 1,
    description: "Two shots of espresso for an extra strong kick.",
    category: "espresso",
    available: true,
    feature: false,
    createdAt: "12:45",
  },
  {
    id: 15,
    title: "Affogato",
    price: 280,
    image: "./assets/feature-3.jpg",
    quantity: 1,
    description: "Hot espresso poured over vanilla ice cream.",
    category: "dessert coffee",
    available: true,
    feature: true,
    createdAt: "13:00",
  },
];

export default products;
